=== Esri/arcgis-js-api/assets/esri/webscene/spec/src/webscene_schema.json
{"title":"Webscene","type":"object","$schema":"http://json-schema.org/draft-07/schema","description":"The web scene data lists the basemap, operational layers, and presentation slides to be used in the web scene. It also contains information about pop-up windows and layer styling overrides to be used in the web scene. A version property allows you to supply the version of the web scene JSON format being used.","properties":{"applicationProperties":{"type":"object","$ref":"applicationProperties_schema.json"},"authoringApp":{"type":"string","description":"String value indicating the application which authored the webmap"},"authoringAppVersion":{"type":"string","description":"String value indicating the authoring App's version number."},"baseMap":{"type":"object","description":"Basemaps give the web scene a geographic context.","$ref":"baseMap_schema.json"},"clippingArea":{"type":"object","$ref":"clippingArea_schema.json"},"ground":{"type":"object","$ref":"ground_schema.json"},"heightModelInfo":{"type":"object","$ref":"heightModelInfo_schema.json"},"initialState":{"type":"object","$ref":"initialState_schema.json"},"mapRangeInfo":{"type":"object","description":"Map Range Information","$ref":"mapRangeInfo_schema.json"},"operationalLayers":{"type":"array","description":"Operational layers contain business data which are used to make thematic scenes.","items":{"type":"object","$ref":"operationalLayers_schema.json"},"uniqueItems":true},"presentation":{"type":"object","$ref":"presentation_schema.json"},"spatialReference":{"type":"object","description":"An object used to specify the spatial reference of the given geometry.","$ref":"spatialReference_schema.json"},"tables":{"type":"array","description":"An array of table objects.","items":{"type":"object","$ref":"table_schema.json"}},"transportationNetworks":{"type":"array","description":"Used to specify the transportation networks of the scene.","items":{"type":"object","$ref":"transportationNetwork_schema.json"}},"version":{"type":"string","description":"Root element in the web scene specifying a string value indicating the web scene version.","$ref":"version_schema.json"},"viewingMode":{"type":"string","enum":["global","local"]},"widgets":{"type":"object","description":"the widgets object contains widgets that should be exposed to the user.","$ref":"widgets_schema.json"}},"required":["ground","operationalLayers","spatialReference","version","viewingMode"],"additionalProperties":false}

=== Esri/arcgis-js-api/assets/esri/webscene/spec/samples/web3dcim_styles.json
{"operationalLayers":[{"id":"148e1a43abe-layer5","listMode":"show","title":"Realistic Trees","url":"https://servicesdev1.arcgis.com/5uh3wwYLNzBuU0Eu/arcgis/rest/services/drivers11/FeatureServer/3","layerType":"ArcGISFeatureLayer","layerDefinition":{"minScale":0,"maxScale":0,"definitionExpression":"OBJECTID<100","elevationInfo":{"mode":"relativeToGround","offset":1},"drawingInfo":{"renderer":{"type":"uniqueValue","visualVariables":[{"type":"sizeInfo","field":"idInt","axis":"height","maxDataValue":82,"maxSize":100,"minDataValue":0,"minSize":20}],"field1":"styleitemname","styleName":"EsriRealisticTreesStyle"}}}},{"id":"148e1a43aa5-layer4","listMode":"show","title":"Thematic Trees","url":"https://servicesdev1.arcgis.com/5uh3wwYLNzBuU0Eu/arcgis/rest/services/drivers11/FeatureServer/2","layerType":"ArcGISFeatureLayer","layerDefinition":{"minScale":0,"maxScale":0,"definitionExpression":"OBJECTID<100","elevationInfo":{"mode":"relativeToGround","offset":1},"drawingInfo":{"renderer":{"type":"uniqueValue","visualVariables":[{"type":"sizeInfo","field":"idInt","axis":"height","maxDataValue":82,"maxSize":100,"minDataValue":0,"minSize":20},{"type":"colorInfo","field":"idInt","stops":[{"color":[255,0,0,255],"value":1},{"color":[0,0,255,255],"value":82}]}],"field1":"styleitemname","styleName":"EsriThematicTreesStyle"}}}},{"id":"148e1a43b03-layer6","listMode":"show","title":"Icons","url":"https://servicesdev1.arcgis.com/5uh3wwYLNzBuU0Eu/arcgis/rest/services/drivers11/FeatureServer/1","layerType":"ArcGISFeatureLayer","layerDefinition":{"minScale":0,"maxScale":0,"definitionExpression":"OBJECTID<41","elevationInfo":{"mode":"relativeToGround","offset":1},"drawingInfo":{"renderer":{"type":"simple","visualVariables":[{"type":"sizeInfo","field":"idInt","axis":"width","maxDataValue":28,"maxSize":32,"minDataValue":1,"minSize":16},{"type":"colorInfo","field":"idInt","stops":[{"color":[255,0,0,255],"value":1},{"color":[0,0,255,255],"value":28}]}],"symbol":{"type":"styleSymbolReference","styleName":"EsriIconsStyle","name":"Airport"}}}}},{"id":"148e1a43a94-layer3","listMode":"show","title":"Thematic Shapes","url":"https://servicesdev1.arcgis.com/5uh3wwYLNzBuU0Eu/arcgis/rest/services/drivers11/FeatureServer/0","layerType":"ArcGISFeatureLayer","layerDefinition":{"minScale":0,"maxScale":0,"elevationInfo":{"mode":"relativeToGround","offset":1},"drawingInfo":{"renderer":{"type":"simple","visualVariables":[{"type":"sizeInfo","field":"idInt","axis":"all","maxDataValue":11,"maxSize":100,"minDataValue":1,"minSize":50},{"type":"colorInfo","field":"idInt","stops":[{"color":[255,0,0,255],"value":1},{"color":[0,0,255,255],"value":11}]}],"symbol":{"type":"styleSymbolReference","styleName":"EsriThematicShapesStyle","name":"Standing Inverted Cone"}}}}}],"baseMap":{"baseMapLayers":[{"id":"14df2e1f61e-layer-197","title":"World Topo Map","url":"https://services.arcgisonline.com/ArcGIS/rest/services/World_Topo_Map/MapServer","layerType":"ArcGISTiledMapServiceLayer"}],"id":"basemap","title":"Topographic","elevationLayers":[{"id":"globalElevation","listMode":"show","title":"Terrain3D","url":"https://elevation3d.arcgis.com/arcgis/rest/services/WorldElevation3D/Terrain3D/ImageServer","layerType":"ArcGISTiledElevationServiceLayer"}]},"ground":{"layers":[{"id":"globalElevation","listMode":"show","title":"Terrain3D","url":"https://elevation3d.arcgis.com/arcgis/rest/services/WorldElevation3D/Terrain3D/ImageServer","layerType":"ArcGISTiledElevationServiceLayer"}],"transparency":0},"version":"1.18","authoringApp":"ArcGIS API for JavaScript","authoringAppVersion":"4.14","initialState":{"environment":{"lighting":{"datetime":1426419727000,"displayUTCOffset":0},"atmosphereEnabled":true,"starsEnabled":true},"viewpoint":{"camera":{"position":{"spatialReference":{"latestWkid":3857,"wkid":102100},"x":497506.4494202166,"y":6788451.43304626,"z":447.0171123743057},"heading":24.317493000981333,"tilt":51.113074376752124}}},"spatialReference":{"latestWkid":3857,"wkid":102100},"viewingMode":"global"}
